name: Release

on:
  # Trigger the workflow on push on the main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

concurrency:
  group: 'release'
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release (dry-run)
        id: release
        # from https://github.com/cycjimmy/semantic-release-action/commits/main
        uses: cycjimmy/semantic-release-action@0a51e81a6baff2acad3ee88f4121c589c73d0f0e # v4.2.0
        with:
          semantic_version: 18.0.0
          dry_run: true
          extra_plugins: |
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Log in to the Container registry
        id: docker_login
        if: steps.release.outputs.new_release_published == 'true'
        # from https://github.com/docker/login-action/commits/master
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (minimal)
        id: docker_build_push_minimal
        if: steps.release.outputs.new_release_published == 'true'
        # from https://github.com/docker/build-push-action/commits/master
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: .
          file: Dockerfile.minimal
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:v${{ steps.release.outputs.new_release_version }}-minimal
          labels: |
            maintainer=https://pagopa.it
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build and push Docker image (full)
        id: docker_build_push_full
        if: steps.release.outputs.new_release_published == 'true'
        # from https://github.com/docker/build-push-action/commits/master
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: .
          file: Dockerfile.full
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest-full
            ghcr.io/${{ github.repository }}:v${{ steps.release.outputs.new_release_version }}-full
          labels: |
            maintainer=https://pagopa.it
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
         
      - name: Release
        id: release
        # from https://github.com/cycjimmy/semantic-release-action/commits/main
        uses: cycjimmy/semantic-release-action@0a51e81a6baff2acad3ee88f4121c589c73d0f0e # v4.2.0
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/git@10.0.1
