name: Test image retagging

on:
  workflow_dispatch:
    inputs:
      current_tag:
        description: Current tag
        required: true
        type: string


jobs:
  retag_image:
    name: Retag Image
    runs-on: ubuntu-22.04

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Image
        id: pull_image
        run: |
          set -euxo pipefail

          docker pull "ghcr.io/${{ github.repository }}:${{ inputs.current_tag }}"


      - name: Retag And Push Image
        id: retag_push_image
        run: |
          set -euxo pipefail

          CURRENT_IMAGE_URI="ghcr.io/${{ github.repository }}:${{ inputs.current_tag }}"
          NEW_IMAGE_URI="ghcr.io/${{ github.repository }}:v1.3.1-retagged"

          docker tag "$CURRENT_IMAGE_URI" "$NEW_IMAGE_URI"
          docker push "$NEW_IMAGE_URI"







