name: Test self-hosted runner

on: workflow_dispatch

permissions:
  contents: read
  id-token: write

jobs:
  create_runner:
    name: Create Self-Hosted Runner
    runs-on: ubuntu-22.04
    outputs:
      runner_name: ${{ steps.start_runner.outputs.runner_name }}

    steps:
      - name: Start GitHub Runner
        id: start_runner
        uses: pagopa/interop-github-runner-aws-create-action@main
        with:
          aws_region: eu-central-1
          iam_role_arn: ${{ secrets.ECS_IAM_ROLE_ARN }}
          ecs_cluster_name: ${{ secrets.ECS_CLUSTER_NAME }}
          ecs_task_definition_arn: ${{ secrets.TASK_DEFINITION_ARN }}
          ecs_container_name: github-runner
          ecs_task_subnet_id: ${{ secrets.SUBNET_ID }}
          ecs_task_sec_group: ${{ secrets.SEC_GROUP_ID }}
          pat_token: ${{ secrets.BOT_TOKEN }}

  test_job:
    name: Test Job
    needs: create_runner
    runs-on: [self-hosted, "${{ needs.create_runner.outputs.runner_name }}"]

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 'Run CLI commands on self hosted runner'
        run: |
          echo "hello world"
          pwd
